spring:
  application:
    name: viewpoint
  datasource:
    url: jdbc:postgresql://localhost:5432/twsa
    username: postgres
    password: 2009
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect